---
title: "Temperature Time Series Analysis"
author: "Austin Guimond"
date: "2022-11-22"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r Jackson Data}
getwd()
#load packages
library(tidyverse)
library(lubridate)
library(zoo)
library(ggplot2)
library(trend)
library(Kendall)
library(tseries)
library(dplyr)

#Load Jackson Temperature Data
Jackson_Raw <- read.csv("~/R/Patton_Guimond_ENV872_Final_Project/Data/Raw Data/Jackson_TenYear.csv",
                         stringsAsFactors = TRUE)
Jackson_Wrangle <- Jackson_Raw %>%
  select(YEAR, MO, DAY, TEMPC) %>%
  mutate('date' = make_date(year = YEAR, month = MO, day = DAY))

#Set as date
Jackson_Summer <- Jackson_Wrangle %>%
  filter(MO== 4 | MO== 5 | MO== 6 | MO== 7 | MO== 8 | MO==9 )
Jackson_Summer$date <- as.Date(Jackson_Summer$date, format = "%y/%m/%d")

#Group by date and find max daily temperature
Daily_High <- Jackson_Summer %>%
  group_by(date) %>% 
  dplyr::summarize(value = max (TEMPC)) %>% 
  as.data.frame()

#Plot max temperatures over time
MaxTemp_Plot <- ggplot(Daily_High, aes(x = date, y = value)) +
  geom_line()+
  geom_smooth(method=lm, col= 'red')+
 ggtitle("Max Temperatures Over Time")+
  xlab("Time (Days)") + ylab("Temperature (C)")
print(MaxTemp_Plot)

#Look for NA values in data and remove
summary(Daily_High$value)
Clean_MaxTemp <- 
  Daily_High %>% 
  mutate(Temp_Clean = zoo::na.approx(value))
summary(Clean_MaxTemp)

#Filter for date and NA omitted Temp
Max_Temp <- Clean_MaxTemp%>%
  select(date, Temp_Clean)
summary(Max_Temp)

#Create Time series object and decompose

Daily_High_ts <- ts(Max_Temp$Temp_Clean, start = c(2012,04,01), frequency = 183)
Daily_High_decomp <- stl(Daily_High_ts,s.window = "periodic")
plot(Daily_High_decomp)

Daily_Temp_Trend <- Kendall::SeasonalMannKendall(Daily_High_ts)
summary(Daily_Temp_Trend)

#Subtract seasonality and run seasonally adjusted Mann Kendall
Daily_Components <- as.data.frame(Daily_High_decomp$time.series[,1:3])

Daily_Components <- mutate(Daily_Components,
        Temp_C = Max_Temp$Temp_Clean,     
        Date = Max_Temp$date)

TempSeasonAdj <- Daily_Components %>%
  mutate(Subtract.Season = Daily_Components$Temp_C - Daily_Components$seasonal)
summary(TempSeasonAdj)

NonSeasonal_Temp_Trend <- Kendall::MannKendall(TempSeasonAdj$Subtract.Season)
summary(NonSeasonal_Temp_Trend)


```


```{r KFSI Data}
#Load KFSI Data
KFSI_Clean <- read.csv("~/R/Patton_Guimond_ENV872_Final_Project/Data/Processed Data/KFSI_Clean.csv",
                         stringsAsFactors = TRUE)
KFSI_Wrangle <- KFSI_Clean %>%
  select(Year, Month, Day, Temperature..F.) %>%
  mutate('date' = make_date(year = Year, month = Month, day = Day)) %>%
           mutate('Temp_C' = ((Temperature..F.-32)/1.8 ))

#Set as date
Summer_KFSI <- KFSI_Wrangle %>%
  filter(Month== 4 | Month== 5 | Month== 6 | Month== 7 | Month== 8 | Month==9 )
Summer_KFSI$date <- as.Date(Summer_KFSI$date, format = "%y/%m/%d")
KFSI_Wrangle_Update <- Summer_KFSI %>%
  select(date, Temp_C)

#Group by date and find max daily temperature
Daily_High_KFSI <- KFSI_Wrangle_Update %>%
  group_by(date) %>% 
  dplyr::summarize(value = max (Temp_C)) %>% 
  as.data.frame()
#Plot max temperatures over time
KFSI_MaxTemp_Plot <- ggplot(Daily_High_KFSI, aes(x = date, y = value)) +
  geom_line()+
  geom_smooth(method=lm, col= 'red')+
 ggtitle("Max Temperatures Over Time")+
  xlab("Time (Days)") + ylab("Temperature (C)")
print(KFSI_MaxTemp_Plot)

#Look for NA values in data and remove
summary(Daily_High_KFSI$value)
KFSI_Filtered_Date <- Daily_High_KFSI %>%
  filter(between(date, as.Date("2012-04-01"), as.Date("2022-09-30")))
#Estimate NA values and filter for date and temperature
Clean_MaxTemp_KSFI <- 
  KFSI_Filtered_Date %>% 
  mutate(Temp_Clean = zoo::na.approx(value))
summary(Clean_MaxTemp_KSFI)
Clean_MaxTemp_KSFI <- Clean_MaxTemp_KSFI %>%
  select(date,Temp_Clean)
summary(Clean_MaxTemp_KSFI)


#Create Time series object and decompose

Daily_High_KFSI_ts <- ts(Clean_MaxTemp_KSFI$Temp_Clean, start = c(2012,04,01), frequency = 183)
Daily_High_KFSI_decomp <- stl(Daily_High_KFSI_ts,s.window = "periodic")
plot(Daily_High_KFSI_ts)
#Run seasonal Mann Kendall Test
Daily_Temp_Trend_KFSI <- Kendall::SeasonalMannKendall(Daily_High_KFSI_ts)
summary(Daily_Temp_Trend_KFSI)

#Subtract seasonality and run seasonally adjusted Mann Kendall
Daily_Components_KFSI <- as.data.frame(Daily_High_KFSI_decomp$time.series[,1:3])
#Create data frame with date, max temp, and daily components
Daily_Components_KFSI <- mutate(Daily_Components_KFSI,
        Temp_C = Clean_MaxTemp_KSFI$Temp_Clean,     
        Date = Clean_MaxTemp_KSFI$date)
#Subtract seasonality 
TempSeasonAdj_KFSI <- Daily_Components_KFSI %>%
  mutate(Subtract.Season = Daily_Components_KFSI$Temp_C - Daily_Components_KFSI$seasonal)
summary(TempSeasonAdj_KFSI)
#Run Mann Kendall test
NonSeasonal_Temp_Trend_KFSI <- Kendall::MannKendall(TempSeasonAdj_KFSI$Subtract.Season)
summary(NonSeasonal_Temp_Trend_KFSI)

```

```{r KLSF Time Series}
#Load KLSF Data
KLSF_Clean <- read.csv("~/R/Patton_Guimond_ENV872_Final_Project/Data/Processed Data/KLSF_Clean.csv",
                         stringsAsFactors = TRUE) 
KLSF_Wrangle <- KLSF_Clean %>%
  select(Year, Month, Day, Temperature..F.) %>%
  mutate('date' = make_date(year = Year, month = Month, day = Day)) %>%
           mutate('Temp_C' = ((Temperature..F.-32)/1.8 ))

#Set as date
Summer_KLSF <- KLSF_Wrangle %>%
  filter(Month== 4 | Month== 5 | Month== 6 | Month== 7 | Month== 8 | Month==9 )
Summer_KLSF$date <- as.Date(Summer_KLSF$date, format = "%y/%m/%d")
KLSF_Wrangle_Update <- Summer_KLSF %>%
  select(date, Temp_C)

#Group by date and find max daily temperature
Daily_High_KLSF <- KLSF_Wrangle_Update %>%
  group_by(date) %>% 
  dplyr::summarize(value = max (Temp_C)) %>% 
  as.data.frame()
#Plot max temperatures over time
KLSF_MaxTemp_Plot <- ggplot(Daily_High_KLSF, aes(x = date, y = value)) +
  geom_line()+
  geom_smooth(method=lm, col= 'red')+
 ggtitle("Max Temperatures Over Time")+
  xlab("Time (Days)") + ylab("Temperature (C)")
print(KLSF_MaxTemp_Plot)

#Look for NA values in data and remove
summary(Daily_High_KLSF$value)
KLSF_Filtered_Date <- Daily_High_KLSF %>%
  filter(between(date, as.Date("2012-04-01"), as.Date("2022-09-30")))
#Estimate NA Dates
Clean_MaxTemp_KLSF <- 
  KLSF_Filtered_Date %>% 
  mutate(Temp_Clean = zoo::na.approx(value))
summary(Clean_MaxTemp_KLSF)
#Select Temperature and date columns 
Clean_MaxTemp_KLSF <- Clean_MaxTemp_KLSF %>%
  select(date,Temp_Clean)
summary(Clean_MaxTemp_KLSF)

#Create Time series object and decompose

Daily_High_KLSF_ts <- ts(Clean_MaxTemp_KLSF$Temp_Clean, start = c(2012,04,01), frequency = 183)
Daily_High_KLSF_decomp <- stl(Daily_High_KLSF_ts,s.window = "periodic")
plot(Daily_High_KLSF_ts)
#Run seasonal Mann Kendall
Daily_Temp_Trend_KLSF <- Kendall::SeasonalMannKendall(Daily_High_KLSF_ts)
summary(Daily_Temp_Trend_KLSF)

#Subtract seasonality and run seasonally adjusted Mann Kendall
Daily_Components_KLSF <- as.data.frame(Daily_High_KLSF_decomp$time.series[,1:3])
#Create data frame with components
Daily_Components_KLSF <- mutate(Daily_Components_KLSF,
        Temp_C = Clean_MaxTemp_KLSF$Temp_Clean,     
        Date = Clean_MaxTemp_KLSF$date)
#Subtract Seasonality
TempSeasonAdj_KLSF <- Daily_Components_KLSF %>%
  mutate(Subtract.Season = Daily_Components_KLSF$Temp_C - Daily_Components_KLSF$seasonal)
summary(TempSeasonAdj_KLSF)
#Run Mann Kendall Test
NonSeasonal_Temp_Trend_KLSF <- Kendall::MannKendall(TempSeasonAdj_KLSF$Subtract.Season)
summary(NonSeasonal_Temp_Trend_KLSF)


```

```{r KTBN}
#Load Data
KTBN_Clean <- read.csv("~/R/Patton_Guimond_ENV872_Final_Project/Data/Processed Data/KTBN_Clean.csv",
                         stringsAsFactors = TRUE) 
KTBN_Wrangle <- KTBN_Clean %>%
  select(Year, Month, Day, Temperature..F.) %>%
  mutate('date' = make_date(year = Year, month = Month, day = Day)) %>%
           mutate('Temp_C' = ((Temperature..F.-32)/1.8 ))

#Set as date
Summer_KTBN <- KTBN_Wrangle %>%
  filter (Month== 4 | Month== 5 | Month== 6 | Month== 7 | Month== 8 | Month==9) 
Summer_KTBN$date <- as.Date(Summer_KTBN$date, format = "%y/%m/%d")
KTBN_Wrangle_Update <- Summer_KTBN %>%
  select(date, Temp_C)

#Group by date and find max daily temperature
Daily_High_KTBN <- KTBN_Wrangle_Update %>%
  group_by(date) %>% 
  dplyr::summarize(value = max (Temp_C)) %>% 
  as.data.frame()
#Plot max temperatures over time
KTBN_MaxTemp_Plot <- ggplot(Daily_High_KTBN, aes(x = date, y = value)) +
  geom_line()+
  geom_smooth(method=lm, col= 'red')+
 ggtitle("Max Temperatures Over Time")+
  xlab("Time (Days)") + ylab("Temperature (C)")
print(KTBN_MaxTemp_Plot)

#Look for NA values in data and remove
summary(Daily_High_KTBN$value)
KTBN_Filtered_Date <- Daily_High_KTBN %>%
  filter(between(date, as.Date("2012-04-01"), as.Date("2022-09-30")))

Clean_MaxTemp_KTBN <- 
  KTBN_Filtered_Date %>% 
  mutate(Temp_Clean = zoo::na.approx(value))
summary(Clean_MaxTemp_KTBN)

Clean_MaxTemp_KTBN <- Clean_MaxTemp_KTBN %>%
    select(date,Temp_Clean)
summary(Clean_MaxTemp_KTBN)

#Create Time series object and decompose

Daily_High_KTBN_ts <- ts(Clean_MaxTemp_KTBN$Temp_Clean, start = c(2012,04,01), frequency = 183)
Daily_High_KTBN_decomp <- stl(Daily_High_KTBN_ts,s.window = "periodic")
plot(Daily_High_KTBN_ts)

Daily_Temp_Trend_KTBN <- Kendall::SeasonalMannKendall(Daily_High_KTBN_ts)
summary(Daily_Temp_Trend_KTBN)

#Subtract seasonality and run seasonally adjusted Mann Kendall
Daily_Components_KTBN <- as.data.frame(Daily_High_KTBN_decomp$time.series[,1:3])

Daily_Components_KTBN <- mutate(Daily_Components_KTBN,
        Temp_C = Clean_MaxTemp_KTBN$Temp_Clean,     
        Date = Clean_MaxTemp_KTBN$date)

TempSeasonAdj_KTBN <- Daily_Components_KTBN %>%
  mutate(Subtract.Season = Daily_Components_KTBN$Temp_C - Daily_Components_KTBN$seasonal)
summary(TempSeasonAdj_KTBN)

NonSeasonal_Temp_Trend_KTBN <- Kendall::MannKendall(TempSeasonAdj_KTBN$Subtract.Season)
summary(NonSeasonal_Temp_Trend_KTBN)
```