---
title: "Time Series"
author: "Austin Guimond"
date: "2022-11-22"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r Jackson Data}
getwd()
#load packages
library(tidyverse)
library(lubridate)
library(zoo)
library(ggplot2)
library(trend)
library(Kendall)
library(tseries)
library(dplyr)
library(formatR)
#install.packages('agricolae')
library(agricolae)
#install.packages('corrplot')
library(corrplot)
install.packages('sf')
install.packages('mapview')
library(mapview)
library(sf)
library(leaflet)

#Load Jackson Data
Jackson_Raw <- read.csv("~/R/Patton_Guimond_ENV872_Final_Project/Jackson_TenYear.csv", 
                         stringsAsFactors = TRUE)

#Code below used to load onto Erik's desktop RStudio
#Jackson_Raw <- read.csv("~/Library/Mobile Documents/com~apple~CloudDocs/R Files/Patton_Guimond_ENV872_Final_Project/Jackson_TenYear.csv", stringsAsFactors = TRUE)

Jackson_Wrangle <- Jackson_Raw %>%
  select(YEAR, MO, DAY, WBGTC) %>%
  mutate('date' = make_date(year = YEAR, month = MO, day = DAY))

#Set as date
Jackson_Wrangle$date <- as.Date(Jackson_Wrangle$date, format = "%y/%m/%d")

#Group by date and find max daily temperature
Daily_High <- Jackson_Wrangle %>%
  group_by(date) %>% 
  dplyr::summarize(value = max (WBGTC)) %>% 
  as.data.frame()
#Plot max temperatures over time
MaxWBTG_Plot <- ggplot(Daily_High, aes(x = date, y = value)) +
  geom_line()+
  geom_smooth(method=lm, col= 'red')+
 ggtitle("Max Wet Bulb Over Time")+
  xlab("Time (Days)") + ylab("Wet Bulb Globe Temperature")
print(MaxWBTG_Plot)

#Look for NA values in data and remove
summary(Daily_High$value)
Clean_WetBulb <- 
  Daily_High %>% 
  mutate(WBGTC_Clean = zoo::na.approx(value))
summary(Clean_WetBulb)

#Filter for date and NA omitted Temp
Max_WetBulb <- Clean_WetBulb%>%
  select(date, WBGTC_Clean)
summary(Max_WetBulb)

#Create Time series object and decompose

Daily_High_ts <- ts(Max_WetBulb$WBGTC_Clean, start = c(2012,01,01), frequency = 365)
Daily_High_decomp <- stl(Daily_High_ts,s.window = "periodic")
plot(Daily_High_decomp)

Daily_WetBulb_Trend <- Kendall::SeasonalMannKendall(Daily_High_ts)
summary(Daily_WetBulb_Trend)

#Subtract seasonality and run seasonally adjusted Mann Kendall
Daily_Components <- as.data.frame(Daily_High_decomp$time.series[,1:3])

Daily_Components <- mutate(Daily_Components,
        WBGTC = Max_WetBulb$WBGTC_Clean,     
        Date = Max_WetBulb$date)

WetBulb_SeasonAdj <- Daily_Components %>%
  mutate(Subtract.Season = Daily_Components$WBGTC - Daily_Components$seasonal)
summary(WetBulb_SeasonAdj)

NonSeasonal_WetBulb_Trend <- Kendall::MannKendall(WetBulb_SeasonAdj$Subtract.Season)
summary(NonSeasonal_WetBulb_Trend)

```


```{r KFSI Data}
#Load Jackson Data
KFSI_Clean <- read.csv("~/R/Patton_Guimond_ENV872_Final_Project/KFSI_Clean.csv",
                         stringsAsFactors = TRUE)
KFSI_Wrangle <- KFSI_Clean %>%
  select(Year, Month, Day, Derived.Wet.Bulb.Globe.Temperature..F.) %>%
  mutate('date' = make_date(year = Year, month = Month, day = Day))

#Set as date
KFSI_Wrangle$date <- as.Date(KFSI_Wrangle$date, format = "%y/%m/%d")
KFSI_Wrangle_Update <- KFSI_Wrangle %>%
  select(date, Derived.Wet.Bulb.Globe.Temperature..F.)

#Group by date and find max daily temperature
Daily_High_KFSI <- KFSI_Wrangle_Update %>%
  group_by(date) %>% 
  dplyr::summarize(value = max (Derived.Wet.Bulb.Globe.Temperature..F.)) %>% 
  as.data.frame()
#Plot max temperatures over time
KFSI_Max_WetBulb_Plot <- ggplot(Daily_High_KFSI, aes(x = date, y = value)) +
  geom_line()+
  geom_smooth(method=lm, col= 'red')+
 ggtitle("Max Wet Bulb Temperatures Over Time")+
  xlab("Time (Days)") + ylab("Wet Bulb (F)")
print(KFSI_Max_WetBulb_Plot)

#Look for NA values in data and remove
summary(Daily_High_KFSI$value)
KFSI_Filtered_Date <- Daily_High_KFSI %>%
  filter(between(date, as.Date("2012-01-10"), as.Date("2022-09-30")))

Clean_Max_WetBulb_KSFI <- 
  KFSI_Filtered_Date %>% 
  mutate(Wet_Bulb = zoo::na.approx(value))
summary(Clean_Max_WetBulb_KSFI)
Clean_Max_WetBulb_KSFI <- Clean_Max_WetBulb_KSFI %>%
  select(date,Wet_Bulb)
summary(Clean_Max_WetBulb_KSFI)


#Create Time series object and decompose

Daily_High_KFSI_ts <- ts(Clean_Max_WetBulb_KSFI$Wet_Bulb, start = c(2012,01,01), frequency = 365)
Daily_High_KFSI_decomp <- stl(Daily_High_KFSI_ts,s.window = "periodic")
plot(Daily_High_KFSI_ts)

Daily_Temp_Trend_KFSI <- Kendall::SeasonalMannKendall(Daily_High_KFSI_ts)
summary(Daily_Temp_Trend_KFSI)

#Subtract seasonality and run seasonally adjusted Mann Kendall
Daily_Components_KFSI <- as.data.frame(Daily_High_KFSI_decomp$time.series[,1:3])

Daily_Components_KFSI <- mutate(Daily_Components_KFSI,
        Wet_Bulb_F = Clean_Max_WetBulb_KSFI$Wet_Bulb,     
        Date = Clean_Max_WetBulb_KSFI$date)

TempSeasonAdj_KFSI <- Daily_Components_KFSI %>%
  mutate(Subtract.Season = Daily_Components_KFSI$Wet_Bulb_F - Daily_Components_KFSI$seasonal)
summary(TempSeasonAdj_KFSI)

NonSeasonal_Temp_Trend_KFSI <- Kendall::MannKendall(TempSeasonAdj_KFSI$Subtract.Season)
summary(NonSeasonal_Temp_Trend_KFSI)

```

```{r KLSF Time Series}
#Load Data
KLSF_Clean <- read.csv("~/R/Patton_Guimond_ENV872_Final_Project/KLSF_Clean.csv",
                         stringsAsFactors = TRUE) 
KLSF_Wrangle <- KLSF_Clean %>%
  select(Year, Month, Day, Derived.Wet.Bulb.Globe.Temperature..F.) %>%
  mutate('date' = make_date(year = Year, month = Month, day = Day)) 
         

#Set as date
KLSF_Wrangle$date <- as.Date(KLSF_Wrangle$date, format = "%y/%m/%d")
KLSF_Wrangle_Update <- KLSF_Wrangle %>%
  select(date, Derived.Wet.Bulb.Globe.Temperature..F.)

#Group by date and find max daily temperature
Daily_High_KLSF <- KLSF_Wrangle_Update %>%
  group_by(date) %>% 
  dplyr::summarize(value = max (Derived.Wet.Bulb.Globe.Temperature..F.)) %>% 
  as.data.frame()
#Plot max temperatures over time
KLSF_Max_Wet_Bulb_Plot <- ggplot(Daily_High_KLSF, aes(x = date, y = value)) +
  geom_line()+
  geom_smooth(method=lm, col= 'red')+
 ggtitle("Max Wet Bulb Temperatures Over Time")+
  xlab("Time (Days)") + ylab("Wet Bulb (F)")
print(KLSF_Max_Wet_Bulb_Plot)

#Look for NA values in data and remove
summary(Daily_High_KLSF$value)
KLSF_Filtered_Date <- Daily_High_KLSF %>%
  filter(between(date, as.Date("2012-01-10"), as.Date("2022-09-30")))

Clean_Max_WetBulb_KLSF <- 
  KLSF_Filtered_Date %>% 
  mutate(Wet_Bulb = zoo::na.approx(value))
summary(Clean_Max_WetBulb_KLSF)

Clean_Max_WetBulb_KLSF <- Clean_Max_WetBulb_KLSF %>%
  select(date,Wet_Bulb)
summary(Clean_Max_WetBulb_KLSF)

#Create Time series object and decompose

Daily_High_KLSF_ts <- ts(Clean_Max_WetBulb_KLSF$Wet_Bulb, start = c(2012,01,01), frequency = 365)
Daily_High_KLSF_decomp <- stl(Daily_High_KLSF_ts,s.window = "periodic")
plot(Daily_High_KLSF_ts)

Daily_Temp_Trend_KLSF <- Kendall::SeasonalMannKendall(Daily_High_KLSF_ts)
summary(Daily_Temp_Trend_KLSF)

#Subtract seasonality and run seasonally adjusted Mann Kendall
Daily_Components_KLSF <- as.data.frame(Daily_High_KLSF_decomp$time.series[,1:3])

Daily_Components_KLSF <- mutate(Daily_Components_KLSF,
        Wet_Bulb = Clean_Max_WetBulb_KLSF$Wet_Bulb,     
        Date = Clean_Max_WetBulb_KLSF$date)

TempSeasonAdj_KLSF <- Daily_Components_KLSF %>%
  mutate(Subtract.Season = Daily_Components_KLSF$Wet_Bulb - Daily_Components_KLSF$seasonal)
summary(TempSeasonAdj_KLSF)

NonSeasonal_Temp_Trend_KLSF <- Kendall::MannKendall(TempSeasonAdj_KLSF$Subtract.Season)
summary(NonSeasonal_Temp_Trend_KLSF)


```

```{r KTBN}
#Load Data
KTBN_Clean <- read.csv("~/R/Patton_Guimond_ENV872_Final_Project/KTBN_Clean.csv",
                         stringsAsFactors = TRUE) 
KTBN_Wrangle <- KTBN_Clean %>%
  select(Year, Month, Day, Derived.Wet.Bulb.Globe.Temperature..F.) %>%
  mutate('date' = make_date(year = Year, month = Month, day = Day))

#Set as date
KTBN_Wrangle$date <- as.Date(KTBN_Wrangle$date, format = "%y/%m/%d")
KTBN_Wrangle_Update <- KTBN_Wrangle %>%
  select(date, Derived.Wet.Bulb.Globe.Temperature..F.)

#Group by date and find max daily temperature
Daily_High_KTBN <- KTBN_Wrangle_Update %>%
  group_by(date) %>% 
  dplyr::summarize(value = max (Derived.Wet.Bulb.Globe.Temperature..F.)) %>% 
  as.data.frame()
#Plot max temperatures over time
KTBN_Max_WetBulb_Plot <- ggplot(Daily_High_KTBN, aes(x = date, y = value)) +
  geom_line()+
  geom_smooth(method=lm, col= 'red')+
 ggtitle("Wet Bulb Temperatures Over Time")+
  xlab("Time (Days)") + ylab("Wet Bulb (F)")
print(KTBN_Max_WetBulb_Plot)

#Look for NA values in data and remove
summary(Daily_High_KTBN$value)
KTBN_Filtered_Date <- Daily_High_KTBN %>%
  filter(between(date, as.Date("2012-01-10"), as.Date("2022-09-30")))

Clean_Max_WetBulb_KTBN <- 
  KTBN_Filtered_Date %>% 
  mutate(Wet_Bulb = zoo::na.approx(value))
summary(Clean_Max_WetBulb_KTBN)

Clean_Max_WetBulb_KTBN <- Clean_Max_WetBulb_KTBN %>%
    select(date,Wet_Bulb)
summary(Clean_Max_WetBulb_KTBN)

#Create Time series object and decompose

Daily_High_KTBN_ts <- ts(Clean_Max_WetBulb_KTBN$Wet_Bulb, start = c(2012,01,01), frequency = 365)
Daily_High_KTBN_decomp <- stl(Daily_High_KLSF_ts,s.window = "periodic")
plot(Daily_High_KTBN_ts)

Daily_WetBulb_Trend_KTBN <- Kendall::SeasonalMannKendall(Daily_High_KTBN_ts)
summary(Daily_WetBulb_Trend_KTBN)

#Subtract seasonality and run seasonally adjusted Mann Kendall
Daily_Components_KTBN <- as.data.frame(Daily_High_KTBN_decomp$time.series[,1:3])

Daily_Components_KTBN <- mutate(Daily_Components_KTBN,
        Wet_Bulb = Clean_Max_WetBulb_KTBN$Wet_Bulb,     
        Date = Clean_Max_WetBulb_KTBN$date)

TempSeasonAdj_KLSF <- Daily_Components_KLSF %>%
  mutate(Subtract.Season = Daily_Components_KLSF$Wet_Bulb - Daily_Components_KLSF$seasonal)
summary(TempSeasonAdj_KLSF)

NonSeasonal_Wet_Bulb_Trend_KLSF <- Kendall::MannKendall(TempSeasonAdj_KLSF$Subtract.Season)
summary(NonSeasonal_Wet_Bulb_Trend_KLSF)
```

```{r, assign values to locations}
sf::sf_use_s2(FALSE)
#FSOK = Fort Sill, Oklahoma
FSOK_KFSI_sfg <- st_point(c(-98.391,34.637))
FSOK_KFSI_sfc <- st_sfc(FSOK_KFSI_sfg, crs=4326)
mapview(FSOK_KFSI_sfc)

#FJSC = Fort Jackson, SC
FJSC_KCUB_sfg <- st_point(c(-81.01,33.99))
FJSC_KCUB_sfc <- st_sfc(FJSC_KCUB_sfg,crs=4326)
mapview(FJSC_KCUB_sfc)

#FLW = Fort Leaonard Wood, MO
FLW_KTBN_sfg <- st_point(c(-92.12,37.75))
FLW_KTBN_sfc <- st_sfc(FLW_KTBN_sfg,crs=4326)
mapview(FLW_KTBN_sfc)

#FBGA = Fort Benning, GA
FBGA_KLSF_sfg <- st_point(c(-84.97,32.35))
FBGA_KLSF_sfc <- st_sfc(FBGA_KLSF_sfg,crs=4326)
mapview(FBGA_KLSF_sfc)

```

